language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "pypy"

services:
    - mongodb

script:
    - python setup.py test

after_success:
    - pip install coveralls
    - coverage run --source=cars setup.py -q tests
    - coveralls

branches:
  only:
    - master

notifications:
    email: false
