language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "pypy"

script:
    - nosetests -s

after_success:
    - pip install coveralls
    - coverage run --source=cars setup.py -q nosetests
    - coveralls

branches:
  only:
    - master

notifications:
    email: false
